export default {
    // 矿和材料
    sliver: { label: '银矿', icon: '/reagens/Silver.webp' },
    marble: { label: '大理石', icon: '/reagens/Marble.webp' },
    psyche: { label: '魂魄', icon: '/reagens/Psyche.webp', },
    nightmare: { label: '梦魇', icon: '/reagens/Nightmare.webp', },
    peral: { label: '珍珠', icon: '/reagens/Pearl.webp', },
    limestone: { label: '石灰岩', icon: '/reagens/Limestone.webp', },
    tears: { label: '泪珠', icon: '/reagens/Tears.webp', },
    fangs: { label: '尖牙', icon: '/reagens/Fangs.webp', },
    fateFabric: { label: '命运丝线', icon: '/reagens/Fate_Fabric.webp', },
    glassrock: { label: '曜石', icon: '/reagens/Glassrock.webp', },
    wool: { label: '羊毛', icon: '/reagens/Wool.webp', },
    iron: { label: '铁矿', icon: '/reagens/Iron.webp', },
    feather: { label: '羽毛', icon: '/reagens/Feather.webp', },
    cinder: { label: '余烬', icon: '/reagens/Cinder.webp', },
    bronze: { label: '青铜', icon: '/reagens/Bronze.webp', },
    shadow: { label: '暗影', icon: '/reagens/Shadow.webp', },
    serpentScales: { label: '蛇鳞', icon: '/reagens/Serpent_Scales.webp', },
    ashes: { label: '尘灰', icon: '/reagens/Ashes.webp', },
    adamant: { label: '精金', icon: '/reagens/Adamant.webp', },
    moonDust: { label: '月尘', icon: '/reagens/MoonDust.png', },
    plasma: { label: '混沌质', icon: '/reagens/Plasma.webp', },
    darkness: { label: '黑暗', icon: '/reagens/Darkness.webp', },
    voidLens: { label: '虚空之眼', icon: '/reagens/Void_Lens.webp', },
    bones: { label: '骨骇', icon: '/reagens/Bones.webp', },
    starDust: { label: '星尘', icon: '/reagens/Star_Dust.webp', },
    zodiacSand: { label: '星尘', icon: '/reagens/Zodiac_Sand.webp', },
    rubbish: { label: '垃圾', icon: '/reagens/Rubbish.webp', },

    // 植物
    lotus: { label: '莲花', icon: '/plants/Lotus.webp', },
    shaderot: { label: '糜影草', icon: '/plants/Shaderot.webp', },
    driftwood: { label: '浮木', icon: '/plants/Driftwood.webp', },
    goldenApple: { label: '金苹果', icon: '/plants/Golden_Apple.webp', },
    nightshade: { label: '颠茄', icon: '/plants/Nightshade.webp', },
    nightshadeSeeds: { label: '颠茄种子', icon: '/plants/Nightshade_Seeds.webp', },
    poppy: { label: '罂粟', icon: '/plants/Poppy.webp', },
    moss: { label: '青苔', icon: '/plants/Moss.webp', },
    mysterySeeds: { label: '神秘种子', icon: '/plants/Mystery_Seeds.webp', },
    olive: { label: '橄榄', icon: '/plants/Olive.webp', },
    moly: { label: '摩吕草', icon: '/plants/Moly.webp', },
    thalamus: { label: '混沌苞蕾', icon: '/plants/Thalamus.webp', },
    cattailSeeds: { label: '香蒲种子', icon: '/plants/Cattail_Seeds.webp', },
    wheatSeeds: { label: '小麦种子', icon: '/plants/Wheat_Seeds.webp', },
    poppySeeds: { label: '罂粟种子', icon: '/plants/Poppy_Seeds.webp', },
    garlicCloves: { label: '蒜瓣', icon: '/plants/Garlic_Cloves.webp', },
    mandrakeSeeds: { label: '曼德拉草种子', icon: '/plants/Mandrake_Seeds.webp', },
    oliveBranch: { label: '橄榄枝', icon: '/plants/Olive_Branch.webp', },
    plankton: { label: '浮游植物', icon: '/plants/Plankton.webp', },
    originSeeds: { label: '原初种子', icon: '/plants/Origin_Seeds.webp', },

    // 人物
    hecate: { label: '赫卡忒', icon: 'hecate_icon.png'  },
    melinoe: { label: '墨利诺厄', icon: 'melinoe_icon.png'  },
    charon: { label: '卡戎', icon: 'charon_icon.png'  },
    moros: { label: '摩罗斯', icon: 'moros_icon.png'  },
    dora: { label: '朵拉', icon: 'dora_icon.png'  },
    circe: { label: '喀尔刻', icon: 'circe_icon.png'  },
    medea: { label: '美狄亚', icon: 'medea_icon.png'  },
    nemesis: { label: '涅墨西斯', icon: 'nemesis_icon.png'  },
    selene: { label: '塞勒涅', icon: 'selene_icon.png'  },
    odysseus: { label: '奥德修斯', icon: 'odysseus_icon.png'  },
    skelly: { label: '瑟勒米乌斯', icon: 'skelly_icon.png'  },
    icarus: { label: '伊卡洛斯', icon: 'icarus_icon.png'  },
    nyx: { label: '倪克斯', icon: 'nyx_icon.png'  },
    zeus: { label: '宙斯', icon: 'zeus_icon.png'  },
    hera: { label: '赫拉', icon: 'hera_icon.png'  },
    poseidon: { label: '波塞冬', icon: 'poseidon_icon.png'  },
    demeter: { label: '德墨忒尔', icon: 'demeter_icon.png'  },
    apollo: { label: '阿波罗', icon: 'apollo_icon.png'  },
    aphrodite: { label: '阿弗洛狄忒', icon: 'aphrodite_icon.png'  },
    hephaestus: { label: '赫菲斯托斯', icon: 'hephaestus_icon.png'  },
    hestia: { label: '赫斯提亚', icon: 'hestia_icon.png'  },
    ares: { label: '阿瑞斯', icon: 'ares_icon.png'  },
    athena: { label: '雅典娜', icon: 'athena_icon.png'  },
    dionysus: { label: '迪奥尼索司', icon: 'dionysus_icon.png'  },
    artemis: { label: '阿尔忒弥斯', icon: 'artemis_icon.png'  },
    hermes: { label: '赫尔墨斯', icon: 'hermes_icon.png'  },
    chronos: { label: '克洛诺斯', icon: 'chronos_icon.png'  },
    hades: { label: '哈迪斯', icon: 'hades_icon.png'  },
    cerberus: { label: '刻耳柏洛斯', icon: 'cerberus_icon.png'  },
    typhon: { label: '提丰', icon: 'typhon_icon.png'  },
    prometheus: { label: '普罗米修斯', icon: 'prometheus_icon.png'  },
    heracles: { label: '赫拉克勒斯', icon: 'heracles_icon.png'  },
    eris: { label: '厄里斯', icon: 'eris_icon.png'  },
    polyphemus: { label: '波吕斐摩斯', icon: 'polyphemus_icon.png'  },
    scylla: { label: '斯库拉', icon: 'scylla_icon.png'  },
    narcissus: { label: '纳西索斯', icon: 'narcissus_icon.png'  },
    arachne: { label: '阿拉克捏', icon: 'arachne_icon.png'  },
    hypnos: { label: '修普诺斯', icon: 'hypnos_icon.png'  },
    zagreus: { label: '扎格列欧斯', icon: 'zagreus_icon.png'  },
    persephone: { label: '泊尔塞福涅', icon: 'persephone_icon.png'  },
    echo: { label: '回声', icon: 'echo_icon.png'  },
    fates: { label: '命运三姐妹', icon: 'fates_icon.png'  },
    chaos: { label: '卡俄斯', icon: 'chaos_icon.png'  },
    
    // 祝福
    premiumService: { label: '尊享服务', icon: '/blessing/hephaestus/Premium_Service.webp', },
    plentifulForage: { label: '生机盎然', icon: '/blessing/demeter/Plentiful_Forage.webp', },
    mixedBlessings: { label: '繁多的祝福', icon: '/blessing/narcissus/Mixed_Blessings.webp', },
    fineLine: { label: '泾渭分明', icon: '/blessing/hera/Fine_Line.webp', },
    oceanSwell: { label: '翻江倒海', icon: '/blessing/poseidon/Ocean_Swell.webp', },

    // 礼物
    nectar: { label: '蜜露', icon: '/goods/Nectar.webp', },
    witchsDelight: { label: '女巫之宝', icon: '/goods/Witch%24s_Delight.webp', },
    
    // 符号
    armor: { label: '护甲', icon: '/values/Armor.webp', },
    health: { label: '生命值', icon: '/values/Health.webp', },
    maxHealth: { label: '生命值上限', icon: '/values/Max_Health.webp', },
    magick: { label: '魔力值', icon: '/values/Magick.webp', },
    maxMagick: { label: '魔力值上限', icon: '/values/Max_Magick.webp', },
    obolPoint: { label: '信用点', icon: '/values/obol_point.png', },
    grasp: { label: '阿卡那悟性', icon: '/values/Grasp.png', },
    deathDefiance: { label: '死里逃生', icon: '/values/Death_Defiance.webp', },
    changeOfFate: { label: '重塑命运', icon: '/values/Change_of_Fate.webp', },
    gold: { label: '金币', icon: '/values/Gold.webp', },
    price: { label: '', icon: '/values/Gold.webp', },
    daedalusHammer: { label: '狄德勒斯之锤', icon: '/values/Daedalus_Hammer.webp', },
    whiles: { label: '', icon: '/values/Whiles.webp', },
    bloodDrop: { label: '血浆', icon: '/values/BloodDrop.png', },
    
    // 元素
    air: { label: '风元素', icon: '/values/Air.webp', },
    fire: { label: '火元素', icon: '/values/Fire.webp', },
    earth: { label: '土元素', icon: '/values/Earth.webp', },
    water: { label: '水元素', icon: '/values/Water.webp', },

    // 咒语
    darkTool: { label: '咒语：暗夜工具' },
    myFriends: { label: '咒语：魔宠信赖' },
    groundMoney: { label: '咒语：大地之财', icon: '' },

    // 魔宠
    frinos: { label: '弗利诺斯', icon: '/friends/Frinos.webp' },
    gale: { label: '加莉', icon: '/friends/Gale.webp' },
    hecuba: { label: '赫库芭', icon: '/friends/Hecuba.webp' },
    raki: { label: '拉奇', icon: '/friends/Raki.webp' },
    toula: { label: '图拉', icon: '/friends/Toula.webp' },
    
    // 工具
    shovel: { label: '银辉铲', icon: '/tools/Shovel.webp' },
    exorcismBook: { label: '安魂石板', icon: '/tools/ExorcismBook.webp' },
    pickaxe: { label: '月牙镐', icon: '/tools/Pickaxe.webp' },
    fishingRod: { label: '钓鱼竿', icon: '/tools/FishingRod.webp', },

    // 炼金釜配方
    makeShadow: { label: '炼金：暗影', icon: '' },
    makeMoon1: { label: '炼金：出影皎月', icon: '' },
    makeMoon2: { label: '炼金：繁星映月', icon: '' },
    sweetNectar: { label: '炼金：甜美蜜露', icon: '' },
    makeWitcDelight: { label: '炼金：女巫之宝', icon: '' },
    returnBorn: { label: '炼金：灵体还阳', icon: '' },
    bigAwake: { label: '炼金：大梦初醒', icon: '' },

    // 其它
    darkTask: { label: '匿踪者之誓 - 忠誓任务', icon: '' },

    // Tag
    funeng: { label: '赋能', icon: '', color:'#dc55e6', textColor: '#fff' },
    legend: { label: '传奇', icon: '', color: '#fc8e28', textColor: '#fff' },
    doubleZeus: { label: '双重祝福 - 宙斯', icon: 'awardsIcon/Zeus_reward.webp', color: '#71915a', textColor: '#fff' },
    doubleHera: { label: '双重祝福 - 赫拉', icon: 'awardsIcon/Hera_reward.webp', color: '#71915a', textColor: '#fff' },
    doublePoseidon: { label: '双重祝福 - 波塞冬', icon: 'awardsIcon/Poseidon_reward.webp', color: '#71915a', textColor: '#fff' },
    doubleDemeter: { label: '双重祝福 - 德墨忒尔', icon: 'awardsIcon/Demeter_reward.webp', color: '#71915a', textColor: '#fff' },
    doubleApollo: { label: '双重祝福 - 阿波罗', icon: 'awardsIcon/Apollo_reward.webp', color: '#71915a', textColor: '#fff' },
    doubleAphrodite: { label: '双重祝福 - 阿弗洛狄忒', icon: 'awardsIcon/Aphrodite_reward.webp', color: '#71915a', textColor: '#fff' },
    doubleHestia: { label: '双重祝福 - 赫斯提亚', icon: 'awardsIcon/Hestia_reward.webp', color: '#71915a', textColor: '#fff' },
    doubleHephaestus: { label: '双重祝福 - 赫菲斯托斯', icon: 'awardsIcon/Hephaestus_reward.webp', color: '#71915a', textColor: '#fff' },
    doubleAres: { label: '双重祝福 - 阿瑞斯', icon: 'awardsIcon/Ares_reward.webp', color: '#71915a', textColor: '#fff' },
    doubleSelene: { label: '双重祝福 - 塞勒涅', icon: 'awardsIcon/Selene_reward.webp', color: '#71915a', textColor: '#fff' },

}