import globalConfigs from "../globalConfigs.mjs"
const { hadesSourceHost } = globalConfigs
export default [
    { label: "银轮", slug: "gifts/silverwheel", attrs: { "data-icon": `${hadesSourceHost}/gifts/Silver_Wheel.webp` }},
    { label: "羊拐骨袋", slug: "gifts/knucklebones", attrs: { "data-icon": `${hadesSourceHost}/gifts/Knuckle_Bones.webp` }},
    { label: "更幸运的牙齿", slug: "gifts/luckiertooth", attrs: { "data-icon": `${hadesSourceHost}/gifts/Luckier_Tooth.webp` }},
    { label: "幽灵洋葱", slug: "gifts/ghostonion", attrs: { "data-icon": `${hadesSourceHost}/gifts/Ghost_Onion.webp` }},
    { label: "邪眼", slug: "gifts/evileye", attrs: { "data-icon": `${hadesSourceHost}/gifts/Evil_Eye.webp` }},
    { label: "零钱包", slug: "gifts/goldpurse", attrs: { "data-icon": `${hadesSourceHost}/gifts/Gold_Purse.webp` }},
    { label: "雕纹胸针", slug: "gifts/engravedpin", attrs: { "data-icon": `${hadesSourceHost}/gifts/Engraved_Pin.webp` }},
    { label: "不谐铃铛", slug: "gifts/discordantbell", attrs: { "data-icon": `${hadesSourceHost}/gifts/Discordant_Bell.webp` }},
    { label: "雪白鹿角", slug: "gifts/whiteantler", attrs: { "data-icon": `${hadesSourceHost}/gifts/White_Antler.webp` }},
    { label: "金属液滴", slug: "gifts/metalicdroplet", attrs: { "data-icon": `${hadesSourceHost}/gifts/Metallic_Droplet.webp` }},
    { label: "皎月光束", slug: "gifts/moonbeam", attrs: { "data-icon": `${hadesSourceHost}/gifts/Moon_Beam.webp` }},
    { label: "云纹手镯", slug: "gifts/cloudbangle", attrs: { "data-icon": `${hadesSourceHost}/gifts/Cloud_Bangle.webp` }},
    { label: "华彩手扇", slug: "gifts/iridescentfan", attrs: { "data-icon": `${hadesSourceHost}/gifts/Iridescent_Fan.webp` }},
    { label: "波漾之海", slug: "gifts/vividsea", attrs: { "data-icon": `${hadesSourceHost}/gifts/Vivid_Sea.webp` }},
    { label: "金穗麦束", slug: "gifts/barleysheaf", attrs: { "data-icon": `${hadesSourceHost}/gifts/Barley_Sheaf.webp` }},
    { label: "和煦光子", slug: "gifts/puresthope", attrs: { "data-icon": `${hadesSourceHost}/gifts/Purest_Hope.webp` }},
    { label: "美丽妆镜", slug: "gifts/beautifulmirror", attrs: { "data-icon": `${hadesSourceHost}/gifts/Beautiful_Mirror.webp` }},
    { label: "精金碎片", slug: "gifts/adamantshard", attrs: { "data-icon": `${hadesSourceHost}/gifts/Adamant_Shard.webp` }},
    { label: "长燃之烬", slug: "gifts/everlastingember", attrs: { "data-icon": `${hadesSourceHost}/gifts/Everlasting_Ember.webp` }},
    { label: "断剑之柄", slug: "gifts/swordhilt", attrs: { "data-icon": `${hadesSourceHost}/gifts/Sword_Hilt.webp` }},
    { label: "蛇发妖护符", slug: "gifts/gorgonamulet", attrs: { "data-icon": `${hadesSourceHost}/gifts/Gorgon_Amulet.webp` }},
    { label: "无花果叶", slug: "gifts/figleaf", attrs: { "data-icon": `${hadesSourceHost}/gifts/Fig_Leaf.webp` }},
    { label: "丝质饰带", slug: "gifts/silkensash", attrs: { "data-icon": `${hadesSourceHost}/gifts/Silken_Sash.webp` }},
    { label: "馥郁小瓶", slug: "gifts/aromaticphial", attrs: { "data-icon": `${hadesSourceHost}/gifts/Aromatic_Phial.webp` }},
    { label: "凹陷之石", slug: "gifts/concavestone", attrs: { "data-icon": `${hadesSourceHost}/gifts/Concave_Stone.webp` }},
    { label: "狮牙", slug: "gifts/lionfang", attrs: { "data-icon": `${hadesSourceHost}/gifts/Lion_Fang.webp` }},
    { label: "黑羊毛", slug: "gifts/blackenedfleece", attrs: { "data-icon": `${hadesSourceHost}/gifts/Blackened_Fleece.webp` }},
    { label: "水晶雕像", slug: "gifts/crystalfigurine", attrs: { "data-icon": `${hadesSourceHost}/gifts/Crystal_Figurine.webp` }},
    { label: "实验之锤", slug: "gifts/experimentalhammer", attrs: { "data-icon": `${hadesSourceHost}/gifts/Experimental_Hammer.webp` }},
    { label: "混沌之胚", slug: "gifts/transcendentembryo", attrs: { "data-icon": `${hadesSourceHost}/gifts/Transcendent_Embryo.webp` }}
]